### ISSUE TITLE
Категории не должны быть захардкожены! Что, если добавить 3ю категорию?

### ISSUE THREAD

**Issue by homich77** [lemki/smart_market#1]
https://github.com/lemki/smart_market/blob/5d147e53acc1eece653e5f1320e8d356ccdc0c45/templates/landing/home.html#L16

https://github.com/lemki/smart_market/blob/5d147e53acc1eece653e5f1320e8d356ccdc0c45/landing/views.py#L12

**Comment by lemki** [comment]
[исправил](https://github.com/lemki/smart_market/commit/5c0d319eb236d086f8bfa3bee26c51ce5e6d5d8e)
