### ISSUE TITLE
Нужно отталкиваться от активного списка продуктов, а не от изображений!

### ISSUE THREAD

**Issue by homich77** [lemki/smart_market#2]
https://github.com/lemki/smart_market/blob/5d147e53acc1eece653e5f1320e8d356ccdc0c45/landing/views.py#L11

**Comment by homich77** [comment]
Тогда не будет ситуации:
если выбрать 3 изображения is_main в одном продукте, то в home выводится 3 продукта

**Comment by lemki** [comment]
[исправил](https://github.com/lemki/smart_market/commit/5c0d319eb236d086f8bfa3bee26c51ce5e6d5d8e)
